version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - curl -fsSL https://get.docker.com | sh
      - sudo usermod -aG docker $USER
      - sudo service docker start
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 091846656105.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-static-app .
      - docker tag my-static-app:latest 091846656105.dkr.ecr.ap-south-1.amazonaws.com/my-static-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 091846656105.dkr.ecr.ap-south-1.amazonaws.com/my-static-app:latest
artifacts:
  files:
    - imagedefinitions.json
